---
- name: stop keepalived_exporter container
  community.docker.docker_container:
    name: keepalived_exporter
    state: stopped
  ignore_errors: true

- name: remove keepalived_exporter container
  community.docker.docker_container:
    name: keepalived_exporter
    state: absent
  ignore_errors: true
