---
- name: Stop keepalived_exporter container
  ignore_errors: true
  community.docker.docker_container:
    name: keepalived_exporter
    state: stopped

- name: Remove keepalived_exporter container
  ignore_errors: true
  community.docker.docker_container:
    name: keepalived_exporter
    state: absent
