---
- name: Install keepalived_exporter
  when:
    - deploy_keepalived_exporter is defined
    - deploy_keepalived_exporter == "install"
  block:
    - name: Include tasks for docker install keepalived_exporter
      when:
        - deploy_keepalived_exporter_mode is defined
        - deploy_keepalived_exporter_mode == "docker"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/install_docker.yml

    - name: Include tasks for binary install keepalived_exporter
      when:
        - deploy_keepalived_exporter_mode is defined
        - deploy_keepalived_exporter_mode == "binary"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/install_binary.yml

    - name: Verify keepalived_exporter is responding to requests
      register: metrics_output
      failed_when: "'Metrics' not in metrics_output.content"
      retries: 6
      delay: 60
      ansible.builtin.uri:
        url: http://127.0.0.1:{{ prometheus_keepalived_exporter_port }}/
        return_content: true


- name: Uninstall keepalived_exporter
  when:
    - deploy_keepalived_exporter is defined
    - deploy_keepalived_exporter == "uninstall"
  block:
    - name: Include tasks for docker uninstall keepalived_exporter
      when:
        - deploy_keepalived_exporter_mode is defined
        - deploy_keepalived_exporter_mode == "docker"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/uninstall_docker.yml

    - name: Include tasks for binary uninstall keepalived_exporter
      when:
        - deploy_keepalived_exporter_mode is defined
        - deploy_keepalived_exporter_mode == "binary"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/uninstall_binary.yml
