---
- name: "install {{ prometheus_keepalived_exporter_name }}"
  block:
    - ansible.builtin.include_tasks:
        file: tasks/sub-tasks/install_docker.yml
      when: deploy_keepalived_exporter_mode is defined
        and
        deploy_keepalived_exporter_mode == "docker"

    - ansible.builtin.include_tasks:
        file: tasks/sub-tasks/install_binary.yml
      when: deploy_keepalived_exporter_mode is defined
        and
        deploy_keepalived_exporter_mode == "binary"

    - name: "verify {{ prometheus_keepalived_exporter_name }} is responding to requests"
      uri:
        url: http://127.0.0.1:{{ prometheus_keepalived_exporter_port }}/
        return_content: true
      register: metrics_output
      failed_when: "'Metrics' not in metrics_output.content"
      retries: 6
      delay: 60

  when: deploy_keepalived_exporter is defined
    and
    deploy_keepalived_exporter == "install"

- name: "uninstall {{ prometheus_keepalived_exporter_name }}"
  block:
    - ansible.builtin.include_tasks:
        file: tasks/sub-tasks/uninstall_docker.yml
      when: deploy_keepalived_exporter_mode is defined
        and
        deploy_keepalived_exporter_mode == "docker"

    - ansible.builtin.include_tasks:
        file: tasks/sub-tasks/uninstall_binary.yml
      when: deploy_keepalived_exporter_mode is defined
        and
        deploy_keepalived_exporter_mode == "binary"

  when: deploy_keepalived_exporter is defined
    and
    deploy_keepalived_exporter == "uninstall"
